services:
  - type: web
    name: youtube-transcript-api
    runtime: python
    repo: https://github.com/JUANPAJR/youtube-transcript-api
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
